import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';

const poppins = Poppins({ weight: ['400', '500', '600'], subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body className={poppins.className}>
				<script
					type='module'
					defer
					src='https://cdn.jsdelivr.net/npm/ldrs@1.0.1/dist/auto/ring.js'
				/>
				<div id='add-url-modal' />
				{children}
			</body>
		</html>
	);
}
